
version: "3"
services:
  base-production:
    container_name: 'be_api'
    hostname: 'be_api'
    image: 'huynhdn/nest-postgres-boilerplate:1.0'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - common

networks:
  common:
    driver: bridge
